### ISSUE TITLE
Need \RequirePackage{xepersian-persiancal}

### ISSUE THREAD

**Issue by OHR64** [persiantex/xepersian#16]
Hi There,
I am trying to use XePersian to write Farsi documents. When compiling the source file, Texmaker
returns the error message "File  xepersian-persiancal not found" . Inside the XePersian style file
I see the command \RequirePackage{xepersian-persiancal}. How can I get this package?

## Check/indicate
- [ ] Relevant to the `bidi` package
- [ ] [The `bidi` package issue tracker](https://github.com/persiantex/bidi/issues) has been searched for similar issues?
- [ ] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{article}            % or some other class

  % Any packages other than the xepersian package must be loaded here

  % The xepersian package must be loaded as the last package
\usepackage[%
    % Any xepersian package option goes here
]{xepersian}
\settextfont{IRXLotus}

  % Any preamble code goes here
  
\begin{document}

  % Demonstration of question here
  
\end{document}
```

**Comment by vafakhalighi** [comment]
Dear GitHub user @OHR64,

The file `xepersian-persiancal.sty` is a part of `xepersian` package and generally when your TeX distribution of choice installs `xepersian` package, the file `xepersian-persiancal.sty` will also be installed and there is no need to manually download this file unless there has been some installation issue. I suggest to reinstall and see if that resolves the issue. Otherwise, you can download it manually from CTAN.

Best wishes, Vafa

**Comment by OHR64** [comment]
Thank you the information and the help
OHR64
