### ISSUE TITLE
setmathdigitfont doesn't work

### ISSUE THREAD

**Issue by bahman-mirzakhani** [persiantex/xepersian#20]
---

## Error for `\setmathdigitfont`
Recently when I updated all packages (especially xepersian-hm), gives an error for \setmathdigitfont command.
## Check/indicate
- [ ] Relevant to the `bidi` package
- [ ] [The `bidi` package issue tracker](https://github.com/persiantex/bidi/issues) has been searched for similar issues?
- [ ] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <http://qa.parsilatex.com/35710/> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode
\documentclass{article}
\usepackage{xepersian}
\settextfont{Amiri}
\setmathdigitfont{Amiri}
\begin{document}
Test
\end{document}
```
[Test.log](https://github.com/persiantex/xepersian/files/5034876/Test.log)

**Comment by da598** [comment]
The same problem here. The old command \setdigitfont was used with a specific font to type hollow-zero in Farsi math relation; after an update it is instructed to use \setmathdigitfont but none seem to work and they generate errors.

**Comment by hadisfr** [comment]
Same as https://github.com/persiantex/xepersian/issues/17.  Take a look at that issue for a fix.

**Comment by da598** [comment]
> Same as #17. Take a look at that issue for a fix.

Did not work for me.

**Comment by hadisfr** [comment]
> Did not work for me.

Did you try https://github.com/persiantex/xepersian/issues/17#issuecomment-669127613 or https://github.com/persiantex/xepersian/pull/19?

Can you provide an minimal working example (code + result) please?

**Comment by mamadhosein** [comment]
my problem was not solved yet,
even by using 
\ExplSyntaxOn \cs_set_eq:NN \etex_iffontchar:D \tex_iffontchar:D \ExplSyntaxOff
before the \setmathdigitfont command.
the errors for me are not mentioning anything about font, but when I remove the \setmathdigitfont command it's all solved at once.

**Comment by vafa-khalighi** [comment]
I sincerely apologize for being very slow and get to this issue quite late.
I have uploaded version 23.2 of the `xepersian` package to CTAN which fixes this issue. You can see the [Release Announcement](https://github.com/tex-persian/xepersian/discussions/1). Please test the new version against this issue; if it indeed fixes the issue, then please close this issue and if it does not, then please let me know what needs to be done so that I can fix it.

Please also note that I had to move the GitHub repository to a new place. The new repository can be found [here](https://github.com/tex-persian/xepersian). If you have reported any issues in the old repository, there is no need to re-report it in the new one but for the new issues, please kindly use the new repository.

There is also a [Discussions](https://github.com/tex-persian/xepersian/discussions) section on the new repository which you can use to ask questions that need my attention. The announcements for future versions of the `xepersian` package also will appear in Discussions under Announcements.

Finally, if you ever need to contact me directly, you can find my email address in the PDF documentation on the second title page.
