### ISSUE TITLE
Incorrect margin display with xepersian and showframe in last update (2021)

### ISSUE THREAD

**Issue by bahman-mirzakhani** [persiantex/xepersian#26]
---

## Brief outline of the issue
Margin display with xepersian and showframe is not correct.
## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ ] [The `xepersian` package issue tracker](https://github.com/persiantex/xepersian/issues) has been searched for similar issues?
- [ ] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode
\documentclass{article} % Also report and book
\usepackage{showframe}
\usepackage{xepersian}
\settextfont{Amiri}
\begin{document}
سلام
\end{document}
```

## Log and PDF files 
[test.log](https://github.com/persiantex/xepersian/files/6277219/test.log)
[test.pdf](https://github.com/persiantex/xepersian/files/6277220/test.pdf)

**Comment by bahman-mirzakhani** [comment]
> ## Brief outline of the issue
> Margin display with xepersian and showframe is not correct.
> 
> ## Check/indicate
> * [ ]  Relevant to the `xepersian` package
> * [ ]  [The `xepersian` package issue tracker](https://github.com/persiantex/xepersian/issues) has been searched for similar issues?
> * [ ]  Issue tracker has been searched for similar issues?
> * [ ]  Links to <tex.stackexchange.com> discussion if appropriate
> * [ ]  Links to <qa.parsilatex.com> discussion if appropriate
> 
> ## Minimal example showing the issue
> ```
> % !TEX TS-program = XeLaTeX
> % !TEX encoding = UTF-8 Unicode
> \documentclass{article} % Also report and book
> \usepackage{showframe}
> \usepackage{xepersian}
> \settextfont{Amiri}
> \begin{document}
> سلام
> \end{document}
> ```
> 
> ## Expected behavior
> ## Log and PDF files
> [test.log](https://github.com/persiantex/xepersian/files/6277219/test.log)
> [test.pdf](https://github.com/persiantex/xepersian/files/6277220/test.pdf)

**Comment by vafa-khalighi** [comment]
I sincerely apologize for being very slow and get to this issue quite late.
I have uploaded version 36.4 of the bidi package to CTAN which fixes this issue. You can see the [Release Announcement](https://github.com/tex-persian/bidi/discussions/1). Please test the new version against this issue; if it indeed fixes the issue, then please close this issue and if it does not, then please let me know what needs to be done so that I can fix it.

Please also note that I had to move the GitHub repository to a new place. The new repository can be found [here](https://github.com/tex-persian/bidi). If you have reported any issues in the old repository, there is no need to re-report it in the new one but for the new issues, please kindly use the new repository.

There is also a [Discussions](https://github.com/tex-persian/bidi/discussions) section on the new repository which you can use to ask questions that need my attention. The announcements for future versions of the bidi package also will appear in Discussions under Announcements.

Finally, if you ever need to contact me directly, you can find my email address in the PDF documentation on the second title page.
